"""Generate ``docs/error_analysis.md`` from the saved eval runs.

Lists the ten worst cases (failed tasks first, then the ones with most verifier
failures / steps) of the newest run of each configuration, with a hypothesis
slot. Numbers come only from ``eval/runs/*.json``.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = REPO_ROOT / "eval" / "runs"
OUT = REPO_ROOT / "docs" / "error_analysis.md"

HYPOTHESES = {
    "form_filling": "pre-filled fields not cleared, wrong radio/checkbox, validation error unnoticed",
    "data_extraction": "value read from the wrong row/column, distractor folder listed, number formatting",
    "web_navigation": "wrong navigation source (sidebar vs breadcrumb), login not completed, search not submitted",
    "multi_step": "dependency skipped (export before upload, unzip before open), attachment not selected",
}


def latest_runs() -> list[dict[str, Any]]:
    """Newest run file per configuration name (excluding the safety ablation)."""
    by_name: dict[str, tuple[str, dict[str, Any]]] = {}
    for path in sorted(RUNS_DIR.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        if "results" not in payload:
            continue
        by_name[payload["name"]] = (path.name, payload)
    return [{"file": f, **p} for f, p in by_name.values()]


def worst_cases(report: dict[str, Any], n: int = 10) -> list[dict[str, Any]]:
    """Rank tasks: failures first, then most verifier failures, then most steps."""
    rows = sorted(
        report["results"],
        key=lambda r: (r["success"], -r["verifier_failures"], -r["steps"], -r["blocked"]),
    )
    return rows[:n]


def render(reports: list[dict[str, Any]]) -> str:
    """Render the markdown document."""
    lines = [
        "# Error analysis",
        "",
        "Generated by `python scripts/error_analysis.py` from `eval/runs/*.json`. The ten worst cases per "
        "configuration are listed (failed first, then most verifier failures, then most steps). "
        "Rows produced without an LLM are marked; the analysis of **real** model failures (recovery "
        "rate, misclicks, hallucinated completion) is pending and needs `ANTHROPIC_API_KEY`.",
        "",
    ]
    for report in reports:
        tag = "fallback determinista, sin LLM" if not report.get("llm_used") else f"LLM {report.get('model')}"
        overall = report["aggregate"]["overall"]
        lines.append(f"## `{report['name']}` — {report['label']} ({tag})")
        lines.append("")
        lines.append(
            f"Source `{report['file']}` · success {overall['success_rate'] * 100:.0f}% "
            f"({int(overall['success_rate'] * overall['n'])}/{overall['n']}) · "
            f"verifier-failure tasks {overall['verifier_failure_tasks']} · blocked {overall['blocked_total']}"
        )
        lines.append("")
        lines.append(
            "| # | Task | Category | Success | Steps | Verifier failures | Last actions | Hypothesis |"
        )
        lines.append("|---|---|---|---|---|---|---|---|")
        for i, row in enumerate(worst_cases(report), start=1):
            last = " → ".join(row["actions"][-3:]).replace("|", "\\|")
            if row["success"]:
                hypothesis = "succeeded; listed only because it is among the longest runs"
            else:
                hypothesis = HYPOTHESES.get(row["category"], "")
            lines.append(
                f"| {i} | `{row['id']}` {row['task'][:60]}… | {row['category']} | "
                f"{'yes' if row['success'] else 'no'} | {row['steps']} | {row['verifier_failures']} | "
                f"{last} | {hypothesis} |"
            )
        lines.append("")
    lines.append("## Failure taxonomy used for the model run (pending)")
    lines.append("")
    lines.append("1. **Misclick** — coordinates off the target; visible as a verifier `FAIL` with no change.")
    lines.append("2. **Wrong element** — a distractor with a similar label (Downloads vs My Documents).")
    lines.append("3. **Premature `task_complete`** — the model claims success; the checker fails.")
    lines.append("4. **Validation loop** — the app shows an inline error the model does not read.")
    lines.append("5. **Extraction error** — wrong row/column or formatting of numbers/e-mails.")
    lines.append("6. **Dependency skipped** — multi-step order broken (upload before export).")
    lines.append("7. **Safety block** — the model tried an action outside the allowed vocabulary.")
    lines.append("8. **Budget exhausted** — `max_steps` reached while making progress.")
    lines.append(
        "9. **Unsupported action** — `left_click_drag` / `hold_key` requested; replaced by a screenshot."
    )
    lines.append(
        "10. **API failure** — retries exhausted (429/5xx); recorded as a run error, not a task failure."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    """Write the document."""
    reports = latest_runs()
    OUT.write_text(render(reports), encoding="utf-8")
    sys.stdout.write(f"wrote {OUT} from {len(reports)} run(s)\n")


if __name__ == "__main__":
    main()
